In [1]:
import findspark
findspark.init()
import pyspark

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Python Spark").master('yarn').getOrCreate()

log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/11/24 19:43:57 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
21/11/24 19:43:57 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
21/11/24 19:43:57 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
21/11/24 19:43:57 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
21/11/24 19:43:57 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
21/11/24 19:43:58 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.


In [3]:
sc = spark.sparkContext # for RDD

In [4]:
spark

In [6]:
from pyspark.mllib.linalg.distributed import RowMatrix, BlockMatrix

In [33]:
import numpy as np

In [15]:
x = RowMatrix(sc.parallelize([[1,1,3],[4,2,6],[6,4,9]]))
y = RowMatrix(sc.parallelize([1,3,6]))

将x，y按axis=1拼接在一起，将xy一同计算xy^T * xy，再进行切片得到xTx和xTy。

In [20]:
xy = RowMatrix(sc.parallelize([[1,1,3,1],[4,2,6,3],[6,4,9,6]]))

In [54]:
xyTxy = xy.computeGramianMatrix().toArray().reshape(4,4)

In [42]:
xTy = xyTxy[:-1, -1]

In [43]:
xTy

array([49., 31., 75.])

In [44]:
xTx = xyTxy[:-1, :-1]

In [45]:
xTx

array([[ 53.,  33.,  81.],
       [ 33.,  21.,  51.],
       [ 81.,  51., 126.]])

In [46]:
beta_hat = np.linalg.solve(xTx, xTy)

In [47]:
beta_hat

array([ 0.5       ,  1.5       , -0.33333333])